[package]
name = "drsandroid"
version = "0.1.0"
authors = ["Alula"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndk = "0.3"
ndk-glue = "0.3"
ndk-sys = "0.2"
doukutsu-rs = { path = "../", default-features = false, features = ["default-base", "backend-glutin"] }
