[package]
authors = ["Alula <julekonopinska@gmail.com>"]
edition = "2018"
name = "doukutsu-rs"
version = "0.1.0"

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.android]
android_version = 28
target_sdk_version = 28
min_sdk_version = 26
build_targets = ["aarch64-linux-android"]
package_name = "io.github.doukutsu_rs.android"
apk_label = "doukutsu-rs"
opengles_version = [2, 0]
fullscreen = true
orientation = "sensorLandscape"
permission = [
    {name = "android.permission.MANAGE_EXTERNAL_STORAGE"},
    {name = "android.permission.READ_EXTERNAL_STORAGE"},
    {name = "android.permission.WRITE_EXTERNAL_STORAGE"}
]
application_metadatas = [
    {name = "android:hardwareAccelerated", value = "true"},
    {name = "android:requestLegacyExternalStorage", value = "true"}
]

[profile.release]
lto = 'thin'
panic = 'abort'

[profile.dev]
opt-level = 1

[dependencies]
#cpal = {path = "./cpal"}
#gfx_device_gl = {path = "./gfx/src/backend/gl"}
#glutin = {path = "./glutin/glutin"}

approx = "0.3"
bitflags = "1"
bitvec = "0.17.4"
byteorder = "1.3"
case_insensitive_hashmap = "1.0.0"
cpal = {git = "https://github.com/doukutsu-rs/cpal.git", branch = "android-support"}
directories = "2"
gfx = "0.18"
gfx_core = "0.9"
gfx_device_gl = {git = "https://github.com/doukutsu-rs/gfx.git", branch = "pre-ll"}
gilrs = "0.7"
glutin = {git = "https://github.com/doukutsu-rs/glutin.git", branch = "android-support"}
imgui = {git = "https://github.com/JMS55/imgui-rs.git"}
imgui-gfx-renderer = {git = "https://github.com/JMS55/imgui-rs.git"}
imgui-winit-support = {git = "https://github.com/JMS55/imgui-rs.git", default-features = false, features = ["winit-23"]}
image = {version = "0.22", default-features = false, features = ["png_codec", "pnm", "bmp"]}
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4"
lru = "0.6.0"
lyon = "0.13"
mint = "0.5"
nalgebra = {version = "0.18", features = ["mint"]}
num-derive = "0.3.2"
num-traits = "0.2.12"
owning_ref = "0.4.1"
paste = "1.0.0"
pretty_env_logger = "0.4.0"
serde = "1"
serde_derive = "1"
smart-default = "0.5"
strum = "0.18.0"
strum_macros = "0.18.0"
toml = "0.5"
varint = "0.9.0"
# remove and replace when drain_filter is in stable
vec_mut_scan = "0.3.0"
webbrowser = "0.5.5"
winit = "0.23.0"

[target.'cfg(target_os = "android")'.dependencies]
ndk = "0.2.0"
ndk-glue = "0.2.0"
jni = "0.17"
