[package]
authors = ["Alula"]
edition = "2018"
name = "doukutsu-rs"
version = "0.1.0"

#[lib]
#crate-type = ["lib", "cdylib"]

[package.metadata.android]
android_version = 29
target_sdk_version = 28
min_sdk_version = 26
build_targets = ["aarch64-linux-android"]
package_name = "io.github.doukutsu_rs.android"
apk_label = "doukutsu-rs"
opengles_version = [3, 1]
fullscreen = true
orientation = "sensorLandscape"
permission = [
    { name = "android.permission.READ_EXTERNAL_STORAGE" },
    { name = "android.permission.WRITE_EXTERNAL_STORAGE" }
]
application_metadatas = [
    { name = "android:hardwareAccelerated", value = "true" },
    { name = "android:requestLegacyExternalStorage", value = "true" }
]

[profile.release]
lto = 'thin'
panic = 'abort'

[profile.dev.package."*"]
opt-level = 3

[profile.dev.build-override]
opt-level = 1

[profile.release.build-override]
opt-level = 1

[features]
default = ["scripting", "backend-sdl"]
backend-sdl = ["sdl2"]
backend-gfx = ["winit", "imgui-gfx-renderer", "imgui-winit-support"]
scripting = ["lua-ffi"]
editor = []

[dependencies]
bitvec = "0.17.4"
byteorder = "1.3"
case_insensitive_hashmap = "1.0.0"
chrono = "0.4"
cpal = { git = "https://github.com/doukutsu-rs/cpal.git", branch = "android-support" }
directories = "3"
imgui = "0.7.0"
imgui-gfx-renderer = { version = "0.7.0", optional = true }
imgui-winit-support = { version = "0.7.0", default-features = false, features = ["winit-23"], optional = true }
image = { version = "0.22", default-features = false, features = ["png_codec", "pnm", "bmp"] }
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4"
lua-ffi = { git = "https://github.com/doukutsu-rs/lua-ffi.git", rev = "1ef3caf772d72068297ddf75df06fd2ef8c1daab", optional = true }
lru = "0.6.0"
num-derive = "0.3.2"
num-traits = "0.2.12"
paste = "1.0.0"
pretty_env_logger = "0.4.0"
sdl2 = { version = "0.34", optional = true, features = ["unsafe_textures", "bundled", "static-link"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_yaml = "0.8"
strum = "0.18.0"
strum_macros = "0.18.0"
# remove and replace when drain_filter is in stable
vec_mut_scan = "0.3.0"
webbrowser = "0.5.5"
winit = { version = "0.24.0", features = ["serde"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target.'cfg(target_os = "android")'.dependencies]
ndk = "0.2"
ndk-glue = "0.2"
jni = "0.17"
