[package]
authors = ["Alula <julekonopinska@gmail.com>"]
edition = "2018"
name = "doukutsu-rs"
version = "0.1.0"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
approx = "0.3"
bitflags = "1"
byteorder = "1.3"
directories = "2"
gfx = "0.18"
gfx_core = "0.9"
gfx_device_gl = "0.16"
gfx_window_glutin = "0.30"
gilrs = "0.7"
glyph_brush = "0.5"
glutin = "0.20"
imgui = "0.4.0"
imgui-ext = "0.3.0"
imgui-gfx-renderer = "0.4.0"
imgui-winit-support =  {version = "0.4.0", default-features = false, features = ["winit-19"] }
image = {version = "0.22", default-features = false, features = ["png_codec", "pnm", "bmp"] }
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4"
lyon = "0.13"
maplit = "1.0.2"
mint = "0.5"
nalgebra = {version = "0.18", features = ["mint"] }
num-traits = "0.2.12"
owning_ref = "0.4.1"
paste = "1.0.0"
pretty_env_logger = "0.4.0"
serde = "1"
serde_derive = "1"
smart-default = "0.5"
strum = "0.18.0"
strum_macros = "0.18.0"
toml = "0.5"
varint = "0.9.0"
winit = { version = "0.19.3" }
